---
#
# Ansible managed
#
repository:
  description: Install rpmfusion repositories on your system.
  homepage: https://buluma.github.io/
  topics: rpmfusion, ansible, molecule, tox, playbook, hacktoberfest
